version: '3.3'

networks:
    traefik:
        external: true

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.3
    container_name: traefik
    restart: always
    environment: 
      - "DUCKDNS_TOKEN=${DUCKDNS_TOKEN}"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      # The HTTPS port
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      # ACME - Let's Encrypt DNS Challenge
      - './letsEncrypt:/letsEncrypt'
      # Entrypoints, routers, middlewares, services, acme configuration
      - './config/:/etc/traefik/'
    networks:
      - "traefik"
  webpage:
    container_name: webpage
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.webpage.loadbalancer.server.port=443"
      - "traefik.http.services.webpage.loadbalancer.server.port=80"
    networks:
      - "traefik"
